//
//  ClipboardMonitor.swift
//  PHTV
//
//  Created by Phạm Hùng Tiến on 2026.
//  Copyright © 2026 Phạm Hùng Tiến. All rights reserved.
//

import AppKit

struct ClipboardHistoryCapturePayload: Equatable, Sendable {
    let textContent: String?
    let imageData: Data?
    let filePaths: [String]?
    let fileReferences: [ClipboardHistoryFileReference]?

    init(
        textContent: String?,
        imageData: Data?,
        filePaths: [String]?,
        fileReferences: [ClipboardHistoryFileReference]? = nil
    ) {
        self.textContent = textContent
        self.imageData = imageData
        self.filePaths = filePaths
        self.fileReferences = fileReferences
    }
}

enum ClipboardHistoryCaptureSanitizer {
    static let maxImageBytes = 5_000_000

    static func sanitizedPayload(
        textContent: String?,
        imageData: Data?,
        filePaths: [String]?,
        fileReferences: [ClipboardHistoryFileReference]? = nil
    ) -> ClipboardHistoryCapturePayload? {
        var sanitizedImageData = imageData
        if let data = sanitizedImageData, data.count > maxImageBytes {
            sanitizedImageData = nil
        }

        let hasText = textContent != nil
        let hasImage = sanitizedImageData != nil
        let hasFiles = !(filePaths?.isEmpty ?? true) || !(fileReferences?.isEmpty ?? true)
        guard hasText || hasImage || hasFiles else { return nil }

        return ClipboardHistoryCapturePayload(
            textContent: textContent,
            imageData: sanitizedImageData,
            filePaths: hasFiles ? filePaths : nil,
            fileReferences: hasFiles ? fileReferences : nil
        )
    }
}

enum ClipboardHistoryPrivacyPolicy {
    /// These markers describe the content, even when a browser extension or a
    /// background password manager wrote it while another app was frontmost.
    static let excludedPasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type"
    ]
    static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    private static let sensitiveBundleIdentifiers: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword",
        "com.bitwarden.desktop",
        "com.lastpass.LastPass",
        "com.dashlane.dashlanephonefinal",
        "org.keepassxc.keepassxc",
        "com.apple.keychainaccess",
        "com.apple.Passwords"
    ]

    static func shouldCaptureContent(
        from bundleIdentifier: String?,
        pasteboardTypes: Set<String> = [],
        declaredSource: String? = nil
    ) -> Bool {
        guard excludedPasteboardTypes.isDisjoint(with: pasteboardTypes) else { return false }
        return [bundleIdentifier, declaredSource].allSatisfy { source in
            guard let source, !source.isEmpty else { return true }
            return !sensitiveBundleIdentifiers.contains(source)
        }
    }
}

struct ClipboardHistoryCaptureRequest: Sendable {
    let itemID: UUID
    let changeCount: Int
    let sourceApp: String?
}

struct ClipboardHistoryPasteboardSnapshot: Sendable {
    let payload: ClipboardHistoryCapturePayload
    let sourceApp: String?
}

/// Reads one pasteboard generation without storing anything. In particular,
/// confidential markers are checked before requesting any promised content.
enum ClipboardHistoryPasteboardReader {
    /// Re-read only metadata before committing. A data provider can add types
    /// while fulfilling content, so a stable changeCount alone is insufficient.
    static func hasEligibleTypes(_ pasteboard: NSPasteboard, sourceApp: String?) -> Bool {
        let types = Set(
            ((pasteboard.types ?? []) + (pasteboard.pasteboardItems ?? []).flatMap(\.types))
                .map(\.rawValue)
        )
        return ClipboardHistoryPrivacyPolicy.shouldCaptureContent(from: sourceApp, pasteboardTypes: types)
    }

    static func read(
        _ pasteboard: NSPasteboard,
        request: ClipboardHistoryCaptureRequest
    ) -> ClipboardHistoryPasteboardSnapshot? {
        func isCurrent() -> Bool {
            !Task.isCancelled && pasteboard.changeCount == request.changeCount
        }

        guard isCurrent() else { return nil }
        let types = Set(
            ((pasteboard.types ?? []) + (pasteboard.pasteboardItems ?? []).flatMap(\.types))
                .map(\.rawValue)
        )
        guard isCurrent(), ClipboardHistoryPrivacyPolicy.shouldCaptureContent(
            from: request.sourceApp, pasteboardTypes: types
        ) else { return nil }

        let declaredSource = pasteboard.string(forType: ClipboardHistoryPrivacyPolicy.sourceType)
        guard isCurrent(), ClipboardHistoryPrivacyPolicy.shouldCaptureContent(
            from: request.sourceApp, pasteboardTypes: types, declaredSource: declaredSource
        ) else { return nil }

        let textContent = pasteboard.string(forType: .string)
        guard isCurrent() else { return nil }

        var imageData: Data?
        if let pngData = pasteboard.data(forType: .png) {
            imageData = pngData
        } else if let tiffData = pasteboard.data(forType: .tiff),
                  let bitmap = NSBitmapImageRep(data: tiffData) {
            imageData = bitmap.representation(using: .png, properties: [:])
        }
        guard isCurrent() else { return nil }

        let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true
        ]) as? [URL]
        guard isCurrent(), hasEligibleTypes(pasteboard, sourceApp: request.sourceApp),
              let payload = ClipboardHistoryCaptureSanitizer.sanitizedPayload(
            textContent: textContent,
            imageData: imageData,
            filePaths: urls?.map(\.path)
        ) else { return nil }

        return ClipboardHistoryPasteboardSnapshot(
            payload: payload,
            sourceApp: declaredSource.flatMap { $0.isEmpty ? nil : $0 } ?? request.sourceApp
        )
    }
}

/// Monitors the system pasteboard for changes and records clipboard history
@MainActor
final class ClipboardMonitor {
    struct Dependencies {
        var changeCount: @MainActor () -> Int
        var sourceApp: @MainActor () -> String?
        var isCaptureSuppressed: @MainActor () -> Bool
        var canCommit: @MainActor (ClipboardHistoryCaptureRequest) -> Bool
        var capture: @Sendable (ClipboardHistoryCaptureRequest) async -> ClipboardHistoryItem?
        var discard: @Sendable (UUID) -> Void
        var store: @MainActor (ClipboardHistoryItem) -> Void
        var didTimeout: @MainActor () -> Void = {}
    }

    static let shared = ClipboardMonitor(dependencies: Dependencies(
        changeCount: { NSPasteboard.general.changeCount },
        sourceApp: { PHTVAppContextService.currentFrontmostBundleId() },
        isCaptureSuppressed: {
            ClipboardHistoryManager.shared.isPasting ||
                PHTVTransientTextInsertionService.isPasteboardMutationActive
        },
        canCommit: { request in
            ClipboardHistoryPasteboardReader.hasEligibleTypes(NSPasteboard.general, sourceApp: request.sourceApp)
        },
        capture: { request in captureCurrentPasteboard(request: request) },
        discard: { ClipboardHistoryFileCache.removeCache(for: $0) },
        store: { ClipboardHistoryManager.shared.addItem($0) },
        didTimeout: {
            PHTVLogger.shared.warning("[ClipboardHistory] Capture timed out; waiting for its worker before retrying")
        }
    ))

    private var monitoringTask: Task<Void, Never>?
    private var captureTask: Task<Void, Never>?
    private var activeCapture: ClipboardHistoryCaptureRequest?
    private var captureInvalidated = false
    private var captureStartedAt: TimeInterval = 0
    private var lastChangeCount: Int?
    private var isMonitoring = false
    private var captureBackoffUntil: TimeInterval = 0

    private let dependencies: Dependencies
    private let pollingInterval: Duration?
    private let captureTimeoutSeconds: TimeInterval
    private let captureBackoffSeconds: TimeInterval
    private let now: @MainActor () -> TimeInterval

    /// Nil pollingInterval lets tests drive the same lifecycle without timers.
    init(
        dependencies: Dependencies,
        pollingInterval: Duration? = .milliseconds(500),
        captureTimeoutSeconds: TimeInterval = 2,
        captureBackoffSeconds: TimeInterval = 5,
        now: @escaping @MainActor () -> TimeInterval = { ProcessInfo.processInfo.systemUptime }
    ) {
        self.dependencies = dependencies
        self.pollingInterval = pollingInterval
        self.captureTimeoutSeconds = captureTimeoutSeconds
        self.captureBackoffSeconds = captureBackoffSeconds
        self.now = now
    }

    var isCapturing: Bool {
        captureTask != nil
    }

    func startMonitoring() {
        guard !isMonitoring else { return }
        isMonitoring = true
        lastChangeCount = dependencies.changeCount()
        guard let pollingInterval else { return }

        monitoringTask = Task { @MainActor [weak self] in
            while !Task.isCancelled {
                try? await Task.sleep(for: pollingInterval)
                guard let self else { break }
                guard !Task.isCancelled, self.isMonitoring else { break }
                self.checkForChanges()
            }
        }
    }

    func stopMonitoring() {
        isMonitoring = false
        monitoringTask?.cancel()
        monitoringTask = nil
        captureInvalidated = true
        captureTask?.cancel()
        // A synchronous pasteboard provider/copy may ignore cancellation. Keep
        // ownership until it returns and its staged files have been discarded.
    }

    func checkForChanges() {
        guard isMonitoring else { return }
        let currentTime = now()
        invalidateTimedOutCapture(at: currentTime)

        guard captureTask == nil, currentTime >= captureBackoffUntil else { return }
        let currentCount = dependencies.changeCount()
        guard currentCount != lastChangeCount else { return }

        lastChangeCount = currentCount

        // Don't capture items that we just pasted from clipboard history.
        guard !dependencies.isCaptureSuppressed() else { return }

        let sourceApp = dependencies.sourceApp()
        guard ClipboardHistoryPrivacyPolicy.shouldCaptureContent(from: sourceApp) else {
            return
        }

        startCapture(ClipboardHistoryCaptureRequest(
            itemID: UUID(), changeCount: currentCount, sourceApp: sourceApp
        ))
    }

    private func invalidateTimedOutCapture(at currentTime: TimeInterval) {
        if activeCapture != nil, !captureInvalidated,
           currentTime - captureStartedAt >= captureTimeoutSeconds {
            captureInvalidated = true
            captureTask?.cancel()
            captureBackoffUntil = currentTime + captureBackoffSeconds
            lastChangeCount = nil
            dependencies.didTimeout()
        }
    }

    private func startCapture(_ request: ClipboardHistoryCaptureRequest) {
        activeCapture = request
        captureInvalidated = false
        captureStartedAt = now()
        let capture = dependencies.capture
        let discard = dependencies.discard
        captureTask = Task.detached(priority: .utility) { [weak self] in
            let item = await capture(request)
            let accepted = await self?.acceptCapture(request, item: item) ?? false
            if !accepted {
                discard(request.itemID)
            }
            await self?.captureWorkerDidFinish(request)
        }
    }

    private func acceptCapture(_ request: ClipboardHistoryCaptureRequest, item: ClipboardHistoryItem?) -> Bool {
        invalidateTimedOutCapture(at: now())
        guard activeCapture?.itemID == request.itemID, !captureInvalidated,
              isMonitoring, !Task.isCancelled,
              now() - captureStartedAt < captureTimeoutSeconds,
              dependencies.changeCount() == request.changeCount,
              !dependencies.isCaptureSuppressed(), dependencies.canCommit(request),
              dependencies.changeCount() == request.changeCount, let item else { return false }
        dependencies.store(item)
        return true
    }

    private func captureWorkerDidFinish(_ request: ClipboardHistoryCaptureRequest) {
        guard activeCapture?.itemID == request.itemID else { return }
        activeCapture = nil
        captureTask = nil
    }

    nonisolated private static func captureCurrentPasteboard(request: ClipboardHistoryCaptureRequest) -> ClipboardHistoryItem? {
        autoreleasepool {
            let pasteboard = NSPasteboard.general
            func isCurrent() -> Bool {
                !Task.isCancelled && pasteboard.changeCount == request.changeCount
            }
            guard let snapshot = ClipboardHistoryPasteboardReader.read(pasteboard, request: request),
                  isCurrent() else { return nil }

            let payload = snapshot.payload
            var fileReferences: [ClipboardHistoryFileReference]?
            if let paths = payload.filePaths, !paths.isEmpty {
                fileReferences = ClipboardHistoryFileCache.references(
                    for: paths.map { URL(fileURLWithPath: $0) },
                    itemID: request.itemID,
                    shouldContinue: isCurrent
                )
            }
            guard isCurrent() else { return nil }

            // Prefer the disk cache. If that write fails, retain the bounded
            // payload so history persistence can preserve it inline instead.
            var imageFilePath: String?
            if let data = payload.imageData {
                imageFilePath = ClipboardHistoryFileCache.saveImageData(data, for: request.itemID)?.path
            }
            guard isCurrent() else { return nil }

            return ClipboardHistoryItem(
                id: request.itemID,
                timestamp: Date(),
                textContent: payload.textContent,
                imageData: imageFilePath == nil ? payload.imageData : nil,
                filePaths: payload.filePaths,
                fileReferences: fileReferences,
                sourceApp: snapshot.sourceApp,
                imageFilePath: imageFilePath
            )
        }
    }
}
