# GitHub Sponsors configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Custom sponsor links
custom: ['https://phamhungtien.com/PHTV/donate.html', 'https://www.paypal.com/paypalme/phamhungtien1404']
