# GitHub Sponsors configuration

# Link Ko-fi (Chỉ điền username)
ko_fi: phamhungtien

# Link PayPal (Chỉ điền username)
paypal: phamhungtien1404

# Link donate trên website cá nhân (Dùng custom)
custom: ['https://phamhungtien.com/PHTV/#donate']
