# GitHub Sponsors configuration

# Tài khoản GitHub chính thức
github: [phamhungtien]

# Link Ko-fi
ko_fi: phamhungtien

# Link PayPal và website được đưa vào mục custom để luôn hiển thị rõ ràng
custom: ['https://paypal.me/phamhungtien1404', 'https://phamhungtien.com/PHTV/#donate']
