# GitHub Sponsors configuration

# Link Ko-fi (sử dụng username sau dấu /)
[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K21SQAPM)

# Link PayPal (sử dụng username sau dấu /)
paypal: phamhungtien1404

# Link donate trên website cá nhân
custom: ['https://phamhungtien.com/PHTV/#donate']
