void vTempOffSpellChecking() {
    if (_useSpellCheckingBefore) {
        setSpellCheckingEnabled(!isSpellCheckingEnabled());
    }
}

void vSetCheckSpelling() {
    _useSpellCheckingBefore = isSpellCheckingEnabled();
}

void vTempOffEngine(const bool& off) {
    _willTempOffEngine = off;
}

bool vRestoreToRawKeys() {
    return restoreToRawKeys();
}

bool checkQuickConsonant() {
    if (_index <= 1) return false;
    const bool quickStartConsonantEnabled = phtvRuntimeQuickStartConsonantEnabled() != 0;
    const bool quickEndConsonantEnabled = phtvRuntimeQuickEndConsonantEnabled() != 0;
    l = 0;
    if (_index > 0) {
        if (quickStartConsonantEnabled && _quickStartConsonant.find(CHR(0)) != _quickStartConsonant.end()) {
            hCode = vRestore;
            hBPC = _index;
            hNCC = _index + 1;
            if (_index < MAX_BUFF-1)
                _index++;
            //right shift
            for (i = _index-1; i >= 2; i--) {
                TypingWord[i] = TypingWord[i-1];
            }
            TypingWord[1] = _quickStartConsonant[CHR(0)][1] | ((TypingWord[0] & CAPS_MASK) && (TypingWord[2] & CAPS_MASK) ? CAPS_MASK : 0);
            TypingWord[0] = _quickStartConsonant[CHR(0)][0] | (TypingWord[0] & CAPS_MASK ? CAPS_MASK : 0);
            l = 1;;
        }
        if (quickEndConsonantEnabled &&
            (_index-2 >= 0 && !IS_CONSONANT(CHR(_index-2))) &&
            _quickEndConsonant.find(CHR(_index-1)) != _quickEndConsonant.end()) {
            hCode = vRestore;
            if (l == 1) {
                hNCC++;
            } else {
                hBPC = 1;
                hNCC = 2;
            }
            if (_index < MAX_BUFF-1)
                _index++;
            TypingWord[_index-1] = _quickEndConsonant[CHR(_index-2)][1] | (TypingWord[_index-2] & CAPS_MASK ? CAPS_MASK : 0);
            TypingWord[_index-2] = _quickEndConsonant[CHR(_index-2)][0] | (TypingWord[_index-2] & CAPS_MASK ? CAPS_MASK : 0);
            
            l = 1;
        }
        if (l == 1) {
            _hasHandleQuickConsonant = true;
            for (i = _index - 1; i >= 0; i--) {
                hData[_index - 1 - i] = GET(TypingWord[i]);
            }
            return true;
        }
    }
    return false;
}
